sudo: false
language: python
dist: trusty
matrix:
  include:
    # lint
    - python: "3.6"
      env: TOX_POSARGS="-e lint"
    # doctest
    - python: "3.6"
      env: TOX_POSARGS="-e doctest"
    # contract
    - python: "3.6"
      env: TOX_POSARGS="-e py36-core"
    # contract
    - python: "3.6"
      env: TOX_POSARGS="-e py36-contract"
cache:
  - pip: true
install:
  - travis_retry pip install pip setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - python --version
  - pip --version
  - pip freeze
script:
  - tox $TOX_POSARGS
